language: python

sudo: required

services:
  - docker

python:
  - 2.7
  
before_install:
  - docker-compose --version

script:
  - docker-compose up --build -d
  - sleep 60
  - docker stop $(docker ps -a -q)
