version: '2'
services:
  queue:
    build: ./framework/queue
    ports:
      - 50000:50000
    cpu_shares: 5
  client:
    build: ./framework/clientapp
    links: 
      - queue
    volumes:
      # host:container
      - ./results:/tmp/results
    cpu_shares: 100
  worker:
    build: ./framework/worker
    links:
      - queue
    volumes:
      # host:container
      - ./results:/tmp/results
    